### ISSUE TITLE
Tried this but it failed with SSO setup

### ISSUE THREAD

**Issue by soocrates** [jabrythehutt/awsrd#30]
Meanwhile i have properly set and worked with SSO
Profile is configured with invalid SSO credentials. Required parameters "sso_account_id", "sso_region", "sso_role_name", "sso_start_url". Got sso_session, sso_account_id, sso_role_name, region, output Reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html

**Comment by jabrythehutt** [comment]
Hey @soocrates I've managed to reproduce the issue and have updated the extension to use the latest AWS SDK so that it's able to resolve SSO credentials.

I used an `~/.aws/config` file of the form:

```
[default]
sso_session = sandbox
sso_account_id = $AWS_ACCOUNT_ID
sso_role_name = $AWS_SSO_ROLE_NAME
region = $AWS_REGION
[sso-session sandbox]
sso_start_url = https://$AWS_SSO_START_HOST/start/#
sso_region = $AWS_REGION
sso_registration_scopes = sso:account:access
```

and signed in with the command `aws sso login` before creating an EC2 instance using the extension.

Please let me know if this doesn't work for you.

**Comment by jabrythehutt** [comment]
@soocrates if this is still a problem please feel free to re-open the issue
